#!/usr/bin/env ansible-playbook
---
# Install basic vim configuration

- hosts: all
  gather_facts: yes

  tasks:

    - name: check prerequisites
      command: which {{ item }}
      register: which_result
      changed_when: false
      with_items:
        - git
        - vim

    - name: create .vim/autoload
      file:
        path: "{{ ansible_user_dir }}/.vim/autoload"
        state: directory

    - name: install plug.vim
      get_url:
        dest: "{{ ansible_user_dir }}/.vim/autoload/plug.vim"
        url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

    - name: copy .vimrc
      copy:
        dest: "{{ ansible_user_dir }}/.vimrc"
        src: vimrc
      register: vimrcfile

    - name: install plugins
      command: vim +PlugInstall +qall
      changed_when: false
      when: vimrcfile|changed
