#!/usr/bin/env ansible-playbook
---
# Install basic vim configuration

- hosts: all
  gather_facts: no

  pre_tasks:
  - setup:
      gather_subset: !all

  tasks:

  - name: check prerequisites
    command: which {{ item }}
    register: which_result
    changed_when: false
    with_items:
      - git
      - vim

  - name: create .vim/ dirs
    file:
      path: "{{ ansible_user_dir }}/.vim/{{item}}"
      state: directory
    with_items:
      - autoload
      - undo

  - name: install plug.vim
    get_url:
      dest: "{{ ansible_user_dir }}/.vim/autoload/plug.vim"
      url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    notify: install plugins

  - name: copy .vimrc
    copy:
      dest: "{{ ansible_user_dir }}/.vimrc"
      src: vimrc
    register: vimrcfile
    notify: install plugins


  handlers:
  - name: install plugins
    command: vim +PlugInstall +qall
    changed_when: false
